name: Test aws

on:
  push:
    branches: [ main, master ]  # Se activa en push a main o master
  pull_request:
    branches: [ main, master ]  # También en PRs hacia estas ramas

jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
    - name: Build the Docker image
      run: docker build -t demian996/frontend-images .
    - name: Push to Dockerhub
      run: docker push demian996/frontend-images:latest
  CD:
    runs-on: ubuntu-latest
    
    steps:
    - name: 🔑 Configurar SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: 🐳 Login a Docker Registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: 🚀 Desplegar en EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST-FRONT }} << 'EOF'
          # Actualizar imágenes
          sudo docker pull demian996/frontend-images:latest
          
          # Detener y limpiar
          sudo docker stop frontend-container || true
          sudo docker rm frontend-container || true
          
          # Ejecutar nuevo contenedor
          sudo docker run -d \
            --name frontend-container \
            -p 80:80 \
            --restart unless-stopped \
            demian996/frontend-images:latest
          
          # Limpieza
          sudo docker system prune -af
        EOF

